// Datos de DEMOSTRACIÓN. Todos los IDs empiezan con "demo-" a propósito para que
// nunca se puedan confundir con datos reales de Supabase (que usan uuid v4).
// Ver docs/07-plan-implementacion.md.
import type {
  Atencion,
  CanjeRecompensa,
  CategoriaGasto,
  CategoriaServicio,
  Cliente,
  ClienteResumen,
  ComisionResumen,
  ConfiguracionFidelizacion,
  Cuenta,
  Gasto,
  MiFidelizacion,
  MovimientoPuntos,
  NotificacionFidelizacion,
  PlantillaGastoRecurrente,
  Profesional,
  Promocion,
  Proveedor,
  Recompensa,
  ReglaPuntos,
  Reserva,
  Servicio,
} from './types'

const hoy = new Date()
function enHoras(h: number) {
  const d = new Date(hoy)
  d.setHours(d.getHours() + h, 0, 0, 0)
  return d.toISOString()
}

export const demoCategorias: CategoriaServicio[] = [
  { id: 'demo-cat-cabello', nombre: 'Cabello', orden_visualizacion: 1, activa: true, descripcion_corta: '[DEMO] Cortes, color y tratamientos.', imagen_url: null, texto_boton: 'Ver servicio', enlace_boton: null },
  { id: 'demo-cat-estetica', nombre: 'Estética', orden_visualizacion: 2, activa: true, descripcion_corta: '[DEMO] Cuidado facial y corporal.', imagen_url: null, texto_boton: 'Ver servicio', enlace_boton: null },
  { id: 'demo-cat-cejas', nombre: 'Cejas y maquillaje', orden_visualizacion: 3, activa: true, descripcion_corta: '[DEMO] Diseño de cejas y maquillaje.', imagen_url: null, texto_boton: 'Ver servicio', enlace_boton: null },
  { id: 'demo-cat-unas', nombre: 'Manicura y pedicura', orden_visualizacion: 4, activa: true, descripcion_corta: '[DEMO] Manicura y pedicura spa.', imagen_url: null, texto_boton: 'Ver servicio', enlace_boton: null },
]

export const demoProfesionales: Profesional[] = [
  {
    id: 'demo-prof-claudia',
    slug: 'claudia',
    nombre: 'Claudia',
    especialidades: ['Color', 'Cortes'],
    bio: '[DEMO] Fundadora del salón, más de 15 años de experiencia en color y cortes.',
    foto_url: null,
    activo: true,
    orden_visualizacion: 1,
    mostrar_en_home: true,
  },
  {
    id: 'demo-prof-naldi',
    slug: 'naldi',
    nombre: 'Naldi',
    especialidades: ['Tratamientos capilares', 'Alisados'],
    bio: '[DEMO] Especialista en tratamientos de recuperación capilar.',
    foto_url: null,
    activo: true,
    orden_visualizacion: 2,
    mostrar_en_home: true,
  },
  {
    id: 'demo-prof-ana',
    slug: 'ana',
    nombre: 'Ana',
    especialidades: ['Cejas', 'Maquillaje'],
    bio: '[DEMO] Diseño de cejas y maquillaje social y de novias.',
    foto_url: null,
    activo: true,
    orden_visualizacion: 3,
    mostrar_en_home: true,
  },
  {
    id: 'demo-prof-valery',
    slug: 'valery',
    nombre: 'Valery',
    especialidades: ['Manicura', 'Pedicura'],
    bio: '[DEMO] Manicura y pedicura spa.',
    foto_url: null,
    activo: true,
    orden_visualizacion: 4,
    mostrar_en_home: true,
  },
]

export const demoServicios: Servicio[] = [
  {
    id: 'demo-serv-corte',
    categoria_id: 'demo-cat-cabello',
    categoria_nombre: 'Cabello',
    nombre: 'Corte de dama',
    descripcion: '[DEMO] Corte y asesoría de imagen.',
    imagen_url: null,
    duracion_minutos: 60,
    tipo_precio: 'fijo',
    precio: 45000,
    activo: true,
    profesionales: [demoProfesionales[0], demoProfesionales[1]],
  },
  {
    id: 'demo-serv-color',
    categoria_id: 'demo-cat-cabello',
    categoria_nombre: 'Cabello',
    nombre: 'Color y tinte',
    descripcion: '[DEMO] El valor final depende del largo y la técnica.',
    imagen_url: null,
    duracion_minutos: 120,
    tipo_precio: 'desde',
    precio: 120000,
    activo: true,
    profesionales: [demoProfesionales[0]],
  },
  {
    id: 'demo-serv-alisado',
    categoria_id: 'demo-cat-cabello',
    categoria_nombre: 'Cabello',
    nombre: 'Alisado / tratamiento capilar',
    descripcion: '[DEMO] Se valora en salón según diagnóstico capilar.',
    imagen_url: null,
    duracion_minutos: 150,
    tipo_precio: 'a_valorar',
    precio: null,
    activo: true,
    profesionales: [demoProfesionales[1]],
  },
  {
    id: 'demo-serv-cejas',
    categoria_id: 'demo-cat-cejas',
    categoria_nombre: 'Cejas y maquillaje',
    nombre: 'Diseño de cejas',
    descripcion: '[DEMO] Perfilado y diseño con henna opcional.',
    imagen_url: null,
    duracion_minutos: 30,
    tipo_precio: 'fijo',
    precio: 25000,
    activo: true,
    profesionales: [demoProfesionales[2]],
  },
  {
    id: 'demo-serv-manicura',
    categoria_id: 'demo-cat-unas',
    categoria_nombre: 'Manicura y pedicura',
    nombre: 'Manicura clásica',
    descripcion: '[DEMO] Manicura con esmaltado tradicional.',
    imagen_url: null,
    duracion_minutos: 45,
    tipo_precio: 'fijo',
    precio: 30000,
    activo: true,
    profesionales: [demoProfesionales[3]],
  },
]

export const demoPromociones: Promocion[] = [
  {
    id: 'demo-promo-cejas',
    nombre: 'Martes de cejas [DEMO]',
    descripcion: 'Diseño de cejas con 20% de descuento todos los martes.',
    condiciones: 'Válido solo los martes, no acumulable.',
    vigente_desde: enHoras(-24 * 10),
    vigente_hasta: enHoras(24 * 30),
    tipo_descuento: 'porcentaje',
    valor: 20,
    activa: true,
    imagen_url: null,
    orden_visualizacion: 1,
    texto_boton: 'Ver promoción',
    enlace_boton: null,
    servicios: ['demo-serv-cejas'],
  },
]

export const demoClienteActual: Cliente = {
  id: 'demo-cliente-1',
  usuario_id: 'demo-usuario-cliente',
  nombre: 'Cliente Demo',
  telefono: '3000000000',
  email: 'demo@example.com',
  consentimiento_marketing: false,
  visitas_completadas: 3,
  gasto_acumulado: 245000,
  activo: true,
  origen_registro: 'admin',
  notas: null,
  resena_google_confirmada: false,
  meta_recompensa_id: null,
  creado_en: enHoras(-720),
}

export const demoReservasCliente: Reserva[] = [
  {
    id: 'demo-reserva-1',
    cliente_id: 'demo-cliente-1',
    servicio_id: 'demo-serv-corte',
    servicio_nombre: 'Corte de dama',
    profesional_id: 'demo-prof-claudia',
    profesional_nombre: 'Claudia',
    rango_inicio: enHoras(26),
    rango_fin: enHoras(27),
    precio_estimado: 45000,
    estado: 'confirmada',
    origen: 'cliente',
    notas: null,
  },
  {
    id: 'demo-reserva-2',
    cliente_id: 'demo-cliente-1',
    servicio_id: 'demo-serv-manicura',
    servicio_nombre: 'Manicura clásica',
    profesional_id: 'demo-prof-valery',
    profesional_nombre: 'Valery',
    rango_inicio: enHoras(-48),
    rango_fin: enHoras(-47),
    precio_estimado: 30000,
    estado: 'completada',
    origen: 'cliente',
    notas: null,
  },
  {
    id: 'demo-reserva-3',
    cliente_id: 'demo-cliente-1',
    servicio_id: 'demo-serv-cejas',
    servicio_nombre: 'Diseño de cejas',
    profesional_id: 'demo-prof-ana',
    profesional_nombre: 'Ana',
    rango_inicio: enHoras(-100),
    rango_fin: enHoras(-99.5),
    precio_estimado: 25000,
    estado: 'cancelada',
    origen: 'cliente',
    notas: null,
  },
]

export const demoHistorialAtenciones: Atencion[] = [
  {
    id: 'demo-atencion-1',
    reserva_id: 'demo-reserva-2',
    cliente_id: 'demo-cliente-1',
    estado: 'completada',
    notas: null,
    creado_en: enHoras(-47),
    completado_en: enHoras(-47),
    lineas: [
      {
        id: 'demo-linea-1',
        servicio_id: 'demo-serv-manicura',
        nombre_snapshot: 'Manicura clásica',
        precio_snapshot: 30000,
        descuento: 0,
        cantidad: 1,
        profesional_id: 'demo-prof-valery',
        profesional_nombre: 'Valery',
      },
    ],
    total_pagado: 30000,
    total_vendido: 30000,
  },
]

// Producto de ejemplo para que el panel admin de Ventas (modo demostración) también muestre
// cómo se ve la tabla de productos vendidos.
export const demoProductosVenta = [
  {
    id: 'demo-prod-1',
    fecha: enHoras(-47),
    clienteNombre: 'Cliente Demo',
    categoria: 'Tratamiento',
    nombre: 'Aceite de cutícula',
    cantidad: 1,
    precioUnitario: 12000,
    subtotal: 12000,
  },
]

export const demoMovimientosPuntos: MovimientoPuntos[] = [
  {
    id: 'demo-mov-1',
    cliente_id: 'demo-cliente-1',
    tipo: 'abono',
    puntos: 240,
    referencia_tipo: 'atencion',
    referencia_id: 'demo-atencion-1',
    canje_id: null,
    motivo: null,
    regla_aplicada: { monto_por_bloque: 1000, puntos_por_bloque: 1, monto_elegible_neto: 240000 },
    creado_en: enHoras(-47),
  },
]

// --- Fidelización: datos de demostración ("Tu belleza florece") ----------------------------

export const demoRecompensas: Recompensa[] = [
  {
    id: 'demo-recompensa-1',
    nombre: 'Hidratación capilar de regalo',
    descripcion: 'Un tratamiento de hidratación profunda, cortesía de la casa.',
    costo_puntos: 300,
    activa: true,
    tipo: 'beneficio',
    servicio_id: 'demo-serv-alisado',
    servicio_nombre: 'Tratamiento capilar',
    monto_descuento: null,
    servicios_elegibles: [],
    condiciones: 'Aplica una vez por clienta cada 60 días.',
    requiere_atencion_pagada: true,
    stock_ilimitado: true,
    cantidad_disponible: null,
    imagen_url: null,
    orden_visualizacion: 0,
    creado_en: enHoras(-2000),
    actualizado_en: enHoras(-2000),
  },
  {
    id: 'demo-recompensa-2',
    nombre: 'Descuento de $15.000',
    descripcion: 'Para usar en cualquier servicio de tu próxima visita.',
    costo_puntos: 400,
    activa: true,
    tipo: 'descuento_fijo',
    servicio_id: null,
    monto_descuento: 15000,
    servicios_elegibles: [],
    condiciones: 'No se combina con otras promociones.',
    requiere_atencion_pagada: true,
    stock_ilimitado: true,
    cantidad_disponible: null,
    imagen_url: null,
    orden_visualizacion: 1,
    creado_en: enHoras(-2000),
    actualizado_en: enHoras(-2000),
  },
]

export const demoConfiguracionFidelizacion: ConfiguracionFidelizacion = {
  acumulacion_activa: true,
  canjes_activo: true,
  texto_programa: 'Gana 1 punto por cada $1.000 en servicios elegibles. Cámbialos por regalos cuando quieras.',
  actualizado_en: enHoras(-2000),
}

export const demoReglaPuntos: ReglaPuntos = {
  id: 'demo-regla-1',
  activa: true,
  vigente_desde: enHoras(-2000),
  vigente_hasta: null,
  monto_por_bloque: 1000,
  puntos_por_bloque: 1,
  categorias_excluidas: [],
  servicios_excluidos: [],
  incluye_productos: true,
}

const demoSaldoFidelizacion = demoMovimientosPuntos.reduce((acc, m) => acc + Number(m.puntos), 0)
const demoMetaFidelizacion = demoRecompensas[1]

export const demoMiFidelizacion: MiFidelizacion = {
  saldo: demoSaldoFidelizacion,
  acumulacion_activa: demoConfiguracionFidelizacion.acumulacion_activa,
  canjes_activo: demoConfiguracionFidelizacion.canjes_activo,
  texto_programa: demoConfiguracionFidelizacion.texto_programa,
  meta: demoMetaFidelizacion,
  progreso: Math.min(Math.max(demoSaldoFidelizacion / demoMetaFidelizacion.costo_puntos, 0), 1),
  puntos_faltantes: Math.max(demoMetaFidelizacion.costo_puntos - demoSaldoFidelizacion, 0),
}

// Un canje reciente sin ver, para poder previsualizar la celebración en desarrollo (modo demo)
// sin tocar puntos de clientas reales — saldo_posterior coincide con demoSaldoFidelizacion a
// propósito, para que se anime en vivo (ver esEventoReciente en lib/fidelizacion/celebracionCanje.ts).
export const demoNotificacionesFidelizacion: NotificacionFidelizacion[] = [
  {
    id: 'demo-notificacion-canje-1',
    cliente_id: demoClienteActual.id,
    tipo: 'canje_confirmado',
    titulo: '¡Disfruta tu recompensa!',
    mensaje: `Usaste ${demoRecompensas[0].costo_puntos} puntos en "${demoRecompensas[0].nombre}".`,
    origen_tipo: 'canje',
    origen_id: 'demo-canje-1',
    leida_en: null,
    creado_en: enHoras(-1),
    datos: {
      canje_id: 'demo-canje-1',
      recompensa_nombre: demoRecompensas[0].nombre,
      recompensa_imagen_url: demoRecompensas[0].imagen_url,
      recompensa_tipo: demoRecompensas[0].tipo,
      costo_puntos: demoRecompensas[0].costo_puntos,
      saldo_anterior: demoSaldoFidelizacion + demoRecompensas[0].costo_puntos,
      saldo_posterior: demoSaldoFidelizacion,
      puntos_ganados_en_esta_atencion: 0,
    },
  },
]

export const demoCanjesCliente: CanjeRecompensa[] = [
  {
    id: 'demo-canje-1',
    cliente_id: demoClienteActual.id,
    recompensa_id: demoRecompensas[0].id,
    atencion_id: null,
    costo_puntos_snapshot: demoRecompensas[0].costo_puntos,
    condiciones_snapshot: {
      nombre: demoRecompensas[0].nombre,
      tipo: demoRecompensas[0].tipo,
      condiciones: demoRecompensas[0].condiciones,
      servicio_id: demoRecompensas[0].servicio_id,
      monto_descuento: demoRecompensas[0].monto_descuento,
    },
    estado: 'confirmado',
    entregado: false,
    empleada_id: null,
    creado_en: enHoras(-1),
    revertido_en: null,
    saldo_anterior: demoSaldoFidelizacion + demoRecompensas[0].costo_puntos,
    saldo_posterior: demoSaldoFidelizacion,
  },
]

// --- Portal de empleadas (demo: sesión como Naldi) ---

export const demoReservasAgendaEmpleada: Reserva[] = [
  {
    id: 'demo-reserva-e1',
    cliente_id: 'demo-cliente-2',
    cliente_nombre: 'Valentina Gómez',
    servicio_id: 'demo-serv-alisado',
    servicio_nombre: 'Tratamiento capilar',
    profesional_id: 'demo-prof-naldi',
    profesional_nombre: 'Naldi',
    rango_inicio: enHoras(1),
    rango_fin: enHoras(3.5),
    precio_estimado: null,
    estado: 'confirmada',
    origen: 'cliente',
    notas: null,
  },
  {
    id: 'demo-reserva-e2',
    cliente_id: 'demo-cliente-3',
    cliente_nombre: 'Daniela Restrepo',
    servicio_id: 'demo-serv-corte',
    servicio_nombre: 'Corte de dama',
    profesional_id: 'demo-prof-naldi',
    profesional_nombre: 'Naldi',
    rango_inicio: enHoras(-2),
    rango_fin: enHoras(-1),
    precio_estimado: 45000,
    estado: 'completada',
    origen: 'cliente',
    notas: null,
  },
]

export const demoComisionesEmpleada: ComisionResumen[] = [
  {
    id: 'demo-com-1',
    atencion_servicio_id: 'demo-linea-e2',
    base_calculo: 45000,
    valor: 18000,
    estado: 'generada',
    creado_en: enHoras(-1),
    servicio_nombre: 'Corte de dama',
    cliente_nombre: 'Daniela Restrepo',
  },
]

// --- Dashboard admin ---

export const demoResumenNegocio = {
  ventasNetas: 3250000,
  cobros: 3100000,
  citasCompletadas: 42,
  clientesNuevos: 7,
  clientesRecurrentes: 28,
  ticketPromedio: 77380,
  cancelaciones: 3,
  inasistencias: 1,
  comisionesGeneradas: 1200000,
  comisionesPendientes: 450000,
}

// Desglose de ventas para las gráficas de pastel del Dashboard (modo demostración): el único
// historial real (demoHistorialAtenciones) trae una sola línea, muy poco para mostrar cómo se
// ven las gráficas, así que aquí se arma un desglose de ejemplo aparte, coherente con
// demoResumenNegocio.ventasNetas pero sin pretender ser la misma atención.
export const demoMetricasVentas = {
  ventasPorProfesional: [
    { etiqueta: 'Claudia', valor: 1180000 },
    { etiqueta: 'Naldi', valor: 850000 },
    { etiqueta: 'Ana', valor: 640000 },
    { etiqueta: 'Valery', valor: 580000 },
  ],
  ventasPorServicio: [
    { etiqueta: 'Color', valor: 900000 },
    { etiqueta: 'Corte de dama', valor: 620000 },
    { etiqueta: 'Tratamiento capilar', valor: 540000 },
    { etiqueta: 'Diseño de cejas', valor: 420000 },
    { etiqueta: 'Manicura clásica', valor: 380000 },
    { etiqueta: 'Otros', valor: 390000 },
  ],
  ventasPorMetodoPago: [
    { etiqueta: 'Transferencia', valor: 1450000 },
    { etiqueta: 'Efectivo', valor: 980000 },
    { etiqueta: 'Tarjeta', valor: 670000 },
  ],
}

export const demoClientesAdmin: ClienteResumen[] = [
  { ...demoClienteActual, ultima_visita: '2026-09-10T15:00:00Z', ultimo_servicio_nombre: 'Corte de dama', ultimo_profesional_nombre: 'Naldi' },
  {
    id: 'demo-cliente-2',
    usuario_id: null,
    nombre: 'Valentina Gómez',
    telefono: '3001112233',
    email: null,
    consentimiento_marketing: false,
    visitas_completadas: 5,
    gasto_acumulado: 380000,
    activo: true,
    origen_registro: 'admin',
    notas: null,
    resena_google_confirmada: true,
    meta_recompensa_id: null,
    creado_en: enHoras(-2000),
    ultima_visita: '2026-08-20T18:00:00Z',
    ultimo_servicio_nombre: 'Color y tinte',
    ultimo_profesional_nombre: 'Claudia',
  },
  {
    id: 'demo-cliente-3',
    usuario_id: null,
    nombre: 'Daniela Restrepo',
    telefono: '3004445566',
    email: null,
    consentimiento_marketing: true,
    visitas_completadas: 2,
    gasto_acumulado: 95000,
    activo: true,
    origen_registro: 'publico',
    notas: null,
    resena_google_confirmada: false,
    meta_recompensa_id: null,
    creado_en: enHoras(-900),
    ultima_visita: null,
    ultimo_servicio_nombre: null,
    ultimo_profesional_nombre: null,
  },
  {
    id: 'demo-cliente-4',
    usuario_id: null,
    nombre: 'Penny Ríos',
    telefono: '3009998877',
    email: null,
    consentimiento_marketing: false,
    visitas_completadas: 0,
    gasto_acumulado: 0,
    activo: true,
    origen_registro: 'admin',
    notas: null,
    resena_google_confirmada: false,
    meta_recompensa_id: null,
    creado_en: enHoras(-1),
    ultima_visita: null,
    ultimo_servicio_nombre: null,
    ultimo_profesional_nombre: null,
  },
]

export const demoEquipoResumen = demoProfesionales.map((p, i) => ({
  ...p,
  ventasDelMes: [1450000, 980000, 620000, 540000][i],
  comisionPendiente: [180000, 120000, 90000, 60000][i],
}))

// --- Gastos y pagos (demo) -----------------------------------------------------------------

function enDias(n: number): string {
  const d = new Date(hoy)
  d.setDate(d.getDate() + n)
  return d.toISOString().slice(0, 10)
}

export const demoCategoriasGasto: CategoriaGasto[] = [
  { id: 'demo-cat-arriendo', nombre: 'Arriendo', activa: true },
  { id: 'demo-cat-servicios', nombre: 'Servicios públicos', activa: true },
  { id: 'demo-cat-internet', nombre: 'Internet y telefonía', activa: true },
  { id: 'demo-cat-aseo', nombre: 'Aseo y lavandería', activa: true },
  { id: 'demo-cat-insumos', nombre: 'Insumos desechables', activa: true },
  { id: 'demo-cat-insumos-general', nombre: 'Insumos', activa: true },
  { id: 'demo-cat-mantenimiento', nombre: 'Mantenimiento', activa: true },
  { id: 'demo-cat-publicidad', nombre: 'Publicidad y marketing', activa: true },
  { id: 'demo-cat-software', nombre: 'Software y suscripciones', activa: true },
  { id: 'demo-cat-transporte', nombre: 'Transporte y domicilios', activa: true },
  { id: 'demo-cat-otros', nombre: 'Otros gastos', activa: true },
]

export const demoCuentas: Cuenta[] = [
  { id: 'demo-cuenta-caja', nombre: 'Caja del salón', tipo: 'efectivo', activa: true, saldo: 1250000 },
  { id: 'demo-cuenta-banco', nombre: 'Banco Bancolombia', tipo: 'bancaria', activa: true, saldo: 4300000 },
]

export const demoProveedoresGasto: Proveedor[] = [
  { id: 'demo-prov-arrendador', nombre: 'Inmobiliaria Central', telefono: '3001234567', activo: true },
  { id: 'demo-prov-epm', nombre: 'EPM', telefono: null, activo: true },
  { id: 'demo-prov-claro', nombre: 'Claro', telefono: null, activo: true },
]

export const demoGastos: Gasto[] = [
  {
    id: 'demo-gasto-arriendo',
    concepto: 'Arriendo local',
    categoria_id: 'demo-cat-arriendo',
    categoria_nombre: 'Arriendo',
    categoria_activa: true,
    proveedor_id: 'demo-prov-arrendador',
    proveedor_nombre: 'Inmobiliaria Central',
    referencia: null,
    fecha: enDias(-2),
    fecha_vencimiento: enDias(-1),
    valor_total: 2200000,
    notas: null,
    comprobante_path: null,
    origen: 'manual',
    referencia_liquidacion_id: null,
    plantilla_id: 'demo-plantilla-arriendo',
    anulado: false,
    anulado_motivo: null,
    anulado_por: null,
    anulado_en: null,
    creado_por: 'demo-usuario-admin',
    creado_por_nombre: 'Claudia (demo)',
    creado_en: enDias(-2),
    actualizado_por: null,
    actualizado_en: enDias(-2),
    total_pagado: 0,
    saldo_pendiente: 2200000,
    estado: 'pendiente',
    vencido: true,
  },
  {
    id: 'demo-gasto-internet',
    concepto: 'Plan de internet y telefonía',
    categoria_id: 'demo-cat-internet',
    categoria_nombre: 'Internet y telefonía',
    categoria_activa: true,
    proveedor_id: 'demo-prov-claro',
    proveedor_nombre: 'Claro',
    referencia: 'FAC-88213',
    fecha: enDias(0),
    fecha_vencimiento: enDias(4),
    valor_total: 189000,
    notas: null,
    comprobante_path: null,
    origen: 'manual',
    referencia_liquidacion_id: null,
    plantilla_id: null,
    anulado: false,
    anulado_motivo: null,
    anulado_por: null,
    anulado_en: null,
    creado_por: 'demo-usuario-admin',
    creado_por_nombre: 'Claudia (demo)',
    creado_en: enDias(0),
    actualizado_por: null,
    actualizado_en: enDias(0),
    total_pagado: 0,
    saldo_pendiente: 189000,
    estado: 'pendiente',
    vencido: false,
  },
  {
    id: 'demo-gasto-insumos',
    concepto: 'Insumos desechables (guantes, toallas)',
    categoria_id: 'demo-cat-insumos',
    categoria_nombre: 'Insumos desechables',
    categoria_activa: true,
    proveedor_id: null,
    proveedor_nombre: null,
    referencia: null,
    fecha: enDias(-5),
    fecha_vencimiento: null,
    valor_total: 320000,
    notas: 'Compra de mostrador, pago mixto.',
    comprobante_path: null,
    origen: 'manual',
    referencia_liquidacion_id: null,
    plantilla_id: null,
    anulado: false,
    anulado_motivo: null,
    anulado_por: null,
    anulado_en: null,
    creado_por: 'demo-usuario-admin',
    creado_por_nombre: 'Claudia (demo)',
    creado_en: enDias(-5),
    actualizado_por: null,
    actualizado_en: enDias(-5),
    total_pagado: 200000,
    saldo_pendiente: 120000,
    estado: 'pago_parcial',
    vencido: false,
  },
  {
    id: 'demo-gasto-servicios',
    concepto: 'Servicios públicos (agua y luz)',
    categoria_id: 'demo-cat-servicios',
    categoria_nombre: 'Servicios públicos',
    categoria_activa: true,
    proveedor_id: 'demo-prov-epm',
    proveedor_nombre: 'EPM',
    referencia: null,
    fecha: enDias(-10),
    fecha_vencimiento: enDias(-8),
    valor_total: 410000,
    notas: null,
    comprobante_path: null,
    origen: 'manual',
    referencia_liquidacion_id: null,
    plantilla_id: null,
    anulado: false,
    anulado_motivo: null,
    anulado_por: null,
    anulado_en: null,
    creado_por: 'demo-usuario-admin',
    creado_por_nombre: 'Claudia (demo)',
    creado_en: enDias(-10),
    actualizado_por: null,
    actualizado_en: enDias(-9),
    total_pagado: 410000,
    saldo_pendiente: 0,
    estado: 'pagado',
    vencido: false,
  },
  {
    id: 'demo-gasto-comisiones',
    concepto: 'Comisiones: Naldi (demo) (periodo quincenal)',
    categoria_id: 'demo-cat-otros',
    categoria_nombre: 'Otros gastos',
    categoria_activa: true,
    proveedor_id: null,
    proveedor_nombre: null,
    referencia: null,
    fecha: enDias(-1),
    fecha_vencimiento: null,
    valor_total: 380000,
    notas: null,
    comprobante_path: null,
    origen: 'liquidacion',
    referencia_liquidacion_id: 'demo-liquidacion-1',
    plantilla_id: null,
    anulado: false,
    anulado_motivo: null,
    anulado_por: null,
    anulado_en: null,
    creado_por: 'demo-usuario-admin',
    creado_por_nombre: 'Claudia (demo)',
    creado_en: enDias(-1),
    actualizado_por: null,
    actualizado_en: enDias(-1),
    total_pagado: 0,
    saldo_pendiente: 380000,
    estado: 'pendiente',
    vencido: false,
  },
  {
    id: 'demo-gasto-anulado',
    concepto: 'Publicidad en redes (cancelada)',
    categoria_id: 'demo-cat-publicidad',
    categoria_nombre: 'Publicidad y marketing',
    categoria_activa: true,
    proveedor_id: null,
    proveedor_nombre: null,
    referencia: null,
    fecha: enDias(-15),
    fecha_vencimiento: null,
    valor_total: 150000,
    notas: null,
    comprobante_path: null,
    origen: 'manual',
    referencia_liquidacion_id: null,
    plantilla_id: null,
    anulado: true,
    anulado_motivo: 'La campaña se canceló antes de pautar.',
    anulado_por: 'demo-usuario-admin',
    anulado_en: enDias(-14),
    creado_por: 'demo-usuario-admin',
    creado_por_nombre: 'Claudia (demo)',
    creado_en: enDias(-15),
    actualizado_por: null,
    actualizado_en: enDias(-14),
    total_pagado: 0,
    saldo_pendiente: 150000,
    estado: 'anulado',
    vencido: false,
  },
]

export const demoPlantillasGastoRecurrente: PlantillaGastoRecurrente[] = [
  {
    id: 'demo-plantilla-arriendo',
    concepto: 'Arriendo local',
    categoria_id: 'demo-cat-arriendo',
    categoria_nombre: 'Arriendo',
    proveedor_id: 'demo-prov-arrendador',
    proveedor_nombre: 'Inmobiliaria Central',
    valor_total: 2200000,
    frecuencia: 'mensual',
    primera_fecha_vencimiento: enDias(-1),
    fecha_fin: null,
    activa: true,
    creado_en: enDias(-90),
  },
  {
    id: 'demo-plantilla-internet',
    concepto: 'Plan de internet y telefonía',
    categoria_id: 'demo-cat-internet',
    categoria_nombre: 'Internet y telefonía',
    proveedor_id: 'demo-prov-claro',
    proveedor_nombre: 'Claro',
    valor_total: 189000,
    frecuencia: 'mensual',
    primera_fecha_vencimiento: enDias(4),
    fecha_fin: null,
    activa: true,
    creado_en: enDias(-60),
  },
]
